DROP TABLE IF EXISTS USER CASCADE;

CREATE TABLE IF NOT EXISTS USER
(
    ID           VARCHAR(20) UNIQUE NOT NULL,
    PASSWORD          VARCHAR(60)        NOT NULL,
    NAME         VARCHAR(60)        NOT NULL,
    PHONE_NUMBER VARCHAR(12)        NOT NULL,
    DEFAULT_ADDR VARCHAR(100)       NOT NULL,
    EMAIL        VARCHAR(60),
    PRIMARY KEY (`ID`)
);