name: Java CI with Gradle

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    env : 
      working-directory: ./demospringioc
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
    - name: Secrets Check
      env: 
        MYSQL_DB_NAME: ${{ secrets.MYSQL_DB_NAME }}
        MYSQL_PASSWORD:  ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_PORT:  ${{ secrets.MYSQL_PORT }}
        MYSQL_URL:  ${{ secrets.MYSQL_URL }}
        MYSQL_USERNAME:  ${{ secrets.MYSQL_USERNAME }}
      run: ./gradlew build
