name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    env : 
      working-directory: ./demospringioc
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Hello world action
      env: 
        MYSQL_PASSWORD:  ${{ secrets.MYSQL_PASSWORD }}
        MYSQL_USERNAME:  ${{ secrets.MYSQL_USERNAME }}
      run: |
        example-command "$MYSQL_PASSWORD"
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
    - name: Build with Gradle
      run: ./gradlew build
      
